---
application:
  name: "tide-tera"
  project: "tide-tera"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "tide-tera-db"
  version: "13"
routers:
- name: "main-tide-tera"
  routes:
  - application_name: "tide-tera"
    paths:
    - "/"