---
application:
  name: "tide-tera"
  project: "tide-tera"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "tide-tera-db"
  version: "12"
routers:
- name: "main-tide-tera"
  custom_domains:
    - branch: main
      domain: tide.jmnorlund.net
  routes:
  - application_name: "tide-tera"
    paths:
    - "/"